#!/usr/bin/env bash
{
    envars=$(mktemp)
    trap "rm $envars" EXIT
    export > "$envars"

    set -o allexport
    [[ -f .env ]] && source ".env" && echo "Sourced .env."
    [[ -f "$envars" ]] && source "$envars" && echo "Reapplied existing envars."
    set +o allexport

    [[ -d .venv ]] && source .venv/bin/activate && echo "Activated venv."

    "$1" "${@:2}"

}

