#!/usr/bin/env python
import os

SEARCH_RESULTS_PATH = os.getenv('SEARCH_RESULTS_PATH')
SEARCH_RESULTS_PARSED = os.getenv('SEARCH_RESULTS_PARSED')

AIRTABLE_RESULTS = os.getenv('AIRTABLE_RESULTS')
AIRTABLE_TO_JSON = os.getenv('AIRTABLE_TO_JSON')

AIRTABLE_TO_QUESTIONS = os.getenv('AIRTABLE_TO_QUESTIONS')
QUERIES_TO_QUESTIONS = os.getenv('QUERIES_TO_QUESTIONS')

SEARCH_RESULTS_JSON = os.getenv("SEARCH_RESULTS_JSON")
AIRTABLE_RESULTS_JSON = os.getenv("AIRTABLE_RESULTS_JSON")
RESULTS = os.getenv('RESULTS')


